### ISSUE TITLE
Uncaught TypeError: this.sunTimes is not a function

### ISSUE THREAD

**Issue by q6276270** [jknlsn/day-and-night#3]
Hi there,
I've seen this bug several times but unfortunately I don't know how to recreate the error. This time the error occurred after waking up from sleep and atom was open during sleep.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [day-and-night](https://github.com/jknlsn/day-and-night) package 0.1.1

### Stack Trace

Uncaught TypeError: this.sunTimes is not a function

```
At /Users/MG/.atom/packages/day-and-night/lib/day-and-night.js:192

TypeError: this.sunTimes is not a function
    at tick (/packages/day-and-night/lib/day-and-night.js:192:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.7.9 
day-and-night 0.1.1 
minimap 4.28.2 
script 3.15.0 
```

**Comment by jknlsn** [comment]
I believe this is fixed in 0.2.3, please reopen if it reoccurs!
